# Generated by Django 6.0.6 on 2026-07-25 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_number', models.CharField(max_length=50, unique=True)),
                ('estimate_date', models.DateField(default=django.utils.timezone.now)),
                ('car_model', models.CharField(blank=True, default='', max_length=100)),
                ('car_number', models.CharField(blank=True, default='', max_length=50)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('validity_days', models.PositiveIntegerField(default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='billing.customer')),
            ],
            options={
                'ordering': ['-estimate_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('PCS', 'PCS'), ('NOS', 'NOS'), ('LTR', 'LTR'), ('KG', 'KG'), ('MTR', 'MTR'), ('SET', 'SET'), ('-', '-')], default='PCS', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.estimate')),
            ],
            options={
                'ordering': ['sr_no'],
            },
        ),
    ]
