# Generated by Django 6.0.6 on 2026-08-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_add_smslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='unit',
            field=models.CharField(choices=[('PCS', 'PCS'), ('NOS', 'NOS'), ('LTR', 'LTR'), ('KG', 'KG'), ('MTR', 'MTR'), ('SET', 'SET'), ('JOB', 'JOB'), ('-', '-')], default='PCS', max_length=10),
        ),
    ]
