# Generated by Django 6.0.6 on 2026-06-27 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(blank=True, default='', max_length=20)),
                ('role', models.CharField(choices=[('Mechanic', 'Mechanic'), ('Helper', 'Helper'), ('Painter', 'Painter'), ('Electrician', 'Electrician'), ('Detailer', 'Detailer'), ('Other', 'Other')], default='Mechanic', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('car_number', models.CharField(blank=True, default='', max_length=50)),
                ('car_model', models.CharField(blank=True, default='', max_length=100)),
                ('work_description', models.TextField()),
                ('wages', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to='billing.invoice')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='workers.worker')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
